### ISSUE TITLE
Some Improvement Ideas (and a request to help)

### ISSUE THREAD

**Issue by IMP1** [glee-uk/virtualcampfire#3]
This issue might need to be split up, and I'm happy for that to happen if you want, but didn't want to spam loads of issues unnecessarily.

There are a couple of UX things I've noticed. 

  - It's unclear why some songs open new tabs with lyrics and others don't, or even that a new tab will be opened when clicking on a song at all. I'd suggest having a column with a link to lyrics.
  - The download button doesn't communicate 'download' to me. It's nice that it's visually cohesive with the play button, but I think it could be more clear from first glance what it does. I suggest using a more well recognised icon for download.
  - The song titles change colour and are indented when hovered, but are not 'focusable' and can't be tabbed through. I suggest making them buttons rather than links (and then styling them as just text) to convey that clicking on them performs an action and add the ability to tab between songs.
  - The player isn't visible anywhere. Once I start a song I cannot stop it! Or scrub through it, or anything.
  - On the player, I'm not sure that looping would be the desired default action for users, but happy to have the discussion around this.

I'm very happy to contribute to this project. I've love a bit of an overview (in the README maybe) of how things are structured and deployed and hosted and whatnot to make it a bit easier to get into doing useful work.

Blue skies,

Huw

P.S maybe also in the sidebar about contributing there could be a link to the songs that don't have recordings yet, so glee groups could fill those gaps?

**Comment by timp** [comment]
Hi Huw, 

All of the above are great suggestions. 

I do not know why it is #3 as yours is the first. 

To track them and respond to them I think they do need to be one issue per Issue. 

Can I close this and you create 7 separate Issues?

**Comment by IMP1** [comment]
Funny that it's number 3. No idea why that is!
But yes, happy to create separate issues for them.

**Comment by IMP1** [comment]
Done this now.
