### ISSUE TITLE
Unclear what clicking on a song will do

### ISSUE THREAD

**Issue by IMP1** [glee-uk/virtualcampfire#4]
I was surprised to find that clicking on a song to play it opened a new tab with the lyrics. I was then also surprised to see that the song continued when I closed the lyrics tab. And then not-too-surprised-but-felt-like-it-didn't-really-fit when I clicked on a song and it didn't have any lyrics.

I suggest that in the table of songs there be a column that says 'Lyrics' or something that opens the new tab (or a modal or something) with the lyrics.

**Comment by timp** [comment]
Explicit lyrics link for songs with lyrics now in place.
