### ISSUE TITLE
Download button doesn't follow conventional icon 'standards'

### ISSUE THREAD

**Issue by IMP1** [glee-uk/virtualcampfire#5]
I think the download button could look more like a download button. And maybe having the file-size next to it would also reinforce the [feedforward](https://en.wikipedia.org/wiki/Feedforward) of the action.

Also, I think there is a (not entirely implemented) [html attribute for `a` tags](https://www.w3schools.com/tags/att_a_download.asp) that could be used for this.

**Comment by timp** [comment]
Changed to an SVG. 
Closing this, happy to receive a new issue.
