### ISSUE TITLE
Player cannot be controlled

### ISSUE THREAD

**Issue by IMP1** [glee-uk/virtualcampfire#7]
The player isn't visible. This means that songs can't be paused/resumed or [scrubbed](https://manual.audacityteam.org/man/scrubbing_and_seeking.html) through.

I suggest adding a player element that can show the current song and some details about it, and show a timeline for how long the song is and how far through the playback is, and can allow actions for pausing, and moving the position of the playback. A site like Soundcloud has this at the bottom of the page, fixed so it's unaffected by scrolling and always on top of the other page content.

Perhaps it could also have a toggle for looping songs.

**Comment by IMP1** [comment]
![example](https://github.com/user-attachments/assets/2932a25d-a240-4333-a963-bbf6b627bea3)

Something like this is vaguely what I mean.

**Comment by timp** [comment]
Player is now visible.
