### ISSUE TITLE
Encourage Glee Contributions

### ISSUE THREAD

**Issue by IMP1** [glee-uk/virtualcampfire#8]
It would be nice if there was a convenient list of missing songs from the site, so that glee groups could deliberately work to fill in those gaps.

Maybe there could also be a way for people to contribute the lyrics to songs that are missing them.

**Comment by timp** [comment]
We need to decide on a lyrics format, but songs without lyrics are now clear.

**Comment by timp** [comment]
https://glee.org.uk/virtualcampfire/Not_Recorded_Yet.html is now automatically generated. 

This is based on file name eg

      Strangest_Dream_(Not_Recorded_Yet).mp3

As we receive the recording this place holder is deleted or renamed.

**Comment by timp** [comment]
The Lyrics are in the PDF at https://glee.org.uk/songbooks/Songbook-2017.pdf
also at https://www.fsc.org.uk/glee/

People can contribute, ideally using the same format as the Example.html
